### ISSUE TITLE
Pimutils fork of khard 

### ISSUE THREAD

**Issue by josephholsten** [pimutils/meta#10]
Khard still has users who are excited to use and contribute to it: https://github.com/scheibler/khard/pull/96

Unfortunately the current maintainer is so inactive, they haven’t found the time to reply to a request to fork in many months: https://github.com/scheibler/khard/issues/144

Is pimutils interested in supporting whatever-khard-becomes? At the very least, we need more than one person with commit access, release access, and authority to grant that access to new maintainers.

**Comment by untitaker** [comment]
It seems like @scheibler replied so it should be fine for now. I'd say we avoid forking.

**Comment by untitaker** [comment]
I'll close this since I don't think there's anything to do from our side.
