### ISSUE TITLE
Move to GHA-based build

### ISSUE THREAD

**Issue by untitaker** [pimutils/meta#15]
The website is currently built so that it is pushed to gh-pages. However, github actions allows you to deploy the build without creating a git branch. Example: https://github.com/untitaker/blog

Unrelated, but I have had problems making github pages provision a TLS certificate for this website. So the way this setup currently works is:

* github pages is configured with pimutils.org CNAME, but does not serve https with correct certificates
* in front there's cloudflare's proxy, which does the actual TLS termination.

I would like to move away from cloudflare. In order to do that, github needs to start serving https correctly. I believe that may be possible if the "more modern" github pages deployment setup is being used. The same issue disappeared on my private blog once I started deploying via the official github pages action.

cc @WhyNotHugo

**Comment by untitaker** [comment]
as soon as i typed this comment, github pages's HTTPS support started working correctly. So we're no longer using cloudflare now. Let's see if the certificate renewal works as well.

**Comment by untitaker** [comment]
the certificate expires on dec 3. I'm going to keep using cloudflare's _nameservers_, because if the site breaks at that date it's super quick and easy to switch to proxying again.

**Comment by WhyNotHugo** [comment]
If TLS renovation breaks, we can quickly switch to [sourcehut pages](https://srht.site/). I'll try to clean up CI by then (notably, stop deploying by creating a `gh-pages` branch).

**Comment by untitaker** [comment]
>If TLS renovation breaks, we can quickly switch to [sourcehut pages](https://srht.site/).

I think that's a conversation we have to have as well. Since you're maintaining vdirsyncer now I'll leave the final decision up to you, but to me sourcehut heightens the barrier to contribution through the way their product is designed. And vdirsyncer could benefit from the opposite of that.

**Comment by WhyNotHugo** [comment]
> but to me sourcehut heightens the barrier to contribution through the way their product is designed.

I'm mostly suggesting pages for hosting websites for now. There's a cli tool to publish from anywhere, so it can be opted-into independently from other services.

In any case, it's just a fallback in case GH screws up for now, not rushing into anything.

**Comment by WhyNotHugo** [comment]
Fixed in https://github.com/pimutils/meta/pull/18
