### ISSUE TITLE
Naming for vdirsyncer rewrite

### ISSUE THREAD

**Issue by WhyNotHugo** [pimutils/meta#25]
Over the last year or two, I've spoken about vdirsyncer to folks at various situations: conferences, meetups, videocalls, etc.

When someone expresses interest and asks for the name of the project, and I spell it out loud, there's always some confusion.

v-dir-syncer doesn't exactly roll off one's tongue. Explaining the `v` part is also not straightforward, since it comes from `vobject` and `vevent`, all terms which are unfamiliar to folks not involved in this domain. I typically end up spelling the name letter by letter.

I have been considering naming the rewrite `pimsync` because of this. I mostly find this name easier to pronounce and communicate, even in a louder/noisier setting. In case of confusion, one can clarify "personal information management", which is also something easier to understand and retain (I hope I'm not being biased here).

Aside from the above scenarios, a name that's easy to remember and pronounce for others _should_ help with potential word-of-mouth when folks when to preach about this tool to their friends.
want to preach

Someone looking for issues/help in future might find content related to the Python implementation, which would add more confusion than it would help. Conversely, having a different name for a rewrite should reduce confusion. 

Finally, having a different name should allow distributions to package both (the existing) vdirsyncer and (the new) pimsync at the same time. The initial release will be lacking a few features (e.g.: Google support, `start_date`, `end_date`), so some users might want to stick to the previous one until those roll out.

I'm not 100% convinced that I want to switch to a new name at this stage. But I'm also not 100% convinced of the opposite.

I'd very much appreciate feedback on this topic, @untitaker, @geier.

**Comment by untitaker** [comment]
given that there's no feature parity I'd actually prefer a distinct name and a move away from it being branded as just "vdirsyncer V2". I think pimsync is good.

**Comment by WhyNotHugo** [comment]
https://whynothugo.nl/journal/2024/11/14/vdirsyncer-status-update-2024-11-renaming-to-pimsync/
