### ISSUE TITLE
pimutils.org

### ISSUE THREAD

**Issue by untitaker** [pimutils/meta#3]
I've registered the domain pimutils.org. I don't really know yet what to put on it, but right now I can't even find a proper static site host that does SSL with own domains. I suspect that GitLab Pages works better in this regard than GitHub's, but if we're about to split up our infrastructure like that, we might as well host on a proper server.

**Comment by untitaker** [comment]
Some other ideas for use:

* Host documentation there. Readthedocs allows for domains. `vdirsyncer.pimutils.org` would replace `vdirsyncer.readthedocs.org`. Same with khal, todoman?
* Some landing page on `pimutils.org` that links to each subdomain. Put the vdir spec from vdirsyncer docs to the main page?

**Comment by untitaker** [comment]
Another option for deployment would be https://5apps.com/

**Comment by untitaker** [comment]
@cgeier @hobarrera Opinions?

**Comment by hobarrera** [comment]
We can have github mirror the repo to gitlab, and have gitlab host
the pages.
This way, our main repo is still in the same place as the rest.
 
 
On Tue, May 24, 2016, at 17:10, Markus Unterwaditzer wrote:
> I've registered the domain pimutils.org. I don't really know yet what
> to put on it, but right now I can't even find a proper static site
> host that does SSL with own domains. I suspect that GitLab Pages
> works better in this regard than GitHub's, but if we're about to
> split up our infrastructure like that, we might as well host on a
> proper server.
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub[1]
>
 
--
Hugo Osvaldo Barrera
 

Links:

  1. https://github.com/pimutils/meta/issues/3

**Comment by geier** [comment]
Quoting Markus Unterwaditzer (2016-05-24 22:26:51)
> Some other ideas for use:
> 
> * Host documentation there. Readthedocs allows for domains. `vdirsyncer.pimutils.org` would replace `vdirsyncer.readthedocs.org`. Same with khal, todoman?
> * Some landing page on `pimutils.org` that links to each subdomain. Put the vdir spec from vdirsyncer docs to the main page?


Sounds good!

**Comment by untitaker** [comment]
We now have git read-only mirrors that update every hour or so, see README in master.

**Comment by geier** [comment]
If I get this right, https://pimutils.org/repos/vdirsyncer should be an example of one of the mirrors, but doesn't work for me (redirect to github).

**Comment by untitaker** [comment]
Fixed! I think I accidentally cloned `https://pimutils.org/vdirsyncer`.

**Comment by untitaker** [comment]
We now have a website. Also I added your keys to the server, so you can ssh into it and have a look. More info in the readme.
