### ISSUE TITLE
Which packages of which versions support python2.7?

### ISSUE THREAD

**Issue by part1zano** [pimutils/meta#6]
For instance, khal 0.8 doesn't, and neither does the fresh vdirsyncer. Could we have a table like the one below about the raised concern?
<table><tr><td>Package</td><td>Version</td><td>Python supported</td></tr>
<tr><td>khal</td><td>0.8</td><td>3.3+</td></tr></table>

**Comment by untitaker** [comment]
| Package | Version | Python supported
-------------------------------------------------
khal | 0.8+ | 3.3+
vdirsyncer | 0.13+ | 3.3+
vdirsyncer | 0.12- (unsupported) | 2.7+, 3.3+
todoman | * | 3+ (?)

**Comment by untitaker** [comment]
The conclusion is pretty simple: Forget all Python versions older than 3.3. Not sure about @geier's policy about support of 0.7.

**Comment by part1zano** [comment]
Question answered. Thank you @untitaker

**Comment by geier** [comment]
I'll backport important fixes to 0.7 for some time (as long as people are interested, upgrading to khal v0.8+ is strongly encouraged where ever the option exists though).
