### ISSUE TITLE
Apply to RGSoC?

### ISSUE THREAD

**Issue by untitaker** [pimutils/meta#8]
https://www.reddit.com/r/Python/comments/5ohv6k/rgsoc_call_for_oss_projects/

I am considering applying the entire pimutils org (or rather, {khal, vdirsyncer, todoman}). @geier says he has no time at that point to be mentoring for khal, but I wonder whether it'd be possible for you @hobarrera? Particularly todoman seems like a good project to get started with because of the relatively clean codebase (and ease to set up, vdirsyncer not really necessary).

Vdirsyncer doesn't appear to be a very beginner-friendly project to me. Also I wouldn't know which open tasks to pick for RGSoC.

**Comment by hobarrera** [comment]
I think all projects are beginner-friendly as far as community/friendlines goes, but yes, `todoman` probably has the simplest codebase (probably due to it's youth and the fact that it's a lot smaller).

You may have noticed I've been replying quite slowly these last months, since I'm settling some RL stuff, but since this is in a few months, I should be settled down, and would be glad to mentor someone into the community.

+1

**Comment by untitaker** [comment]
I can do mentoring for todoman as well, though in any case we need a list of
major features that you envision.

**Comment by untitaker** [comment]
A possible feature for todoman would be a reminder daemon that also watches the tasklists for new entries etc.

**Comment by hobarrera** [comment]
Yup, a daemon (maybe a feature, maybe an external app that uses it) that runs a custom command sounds really useful. I wonder if `khal` could have the same thing for upcoming events.

There's also the daemon mode for `vdirsyncer`, but I guess that might be too complicated. :(

**Comment by untitaker** [comment]
Indeed an external program that handles VALARMS just like VTODOs would be nice. Some challenges:
  - don't just spawn a thread for each scheduled notification
  - don't just scan every `n` seconds for tasks that need notifications
  - take change of the system time into consideration (just `sleep(x)` won't work)

**Comment by geier** [comment]
depending on their definition of fun, [RFC 5546](https://tools.ietf.org/html/rfc5546) support could be a nice challenge (though its probably too hard for total beginners)

**Comment by untitaker** [comment]
I think we need a few more possible projects such that teams have a choice.

The deadline is at the end of this month.

On 24 January 2017 23:11:09 CET, Christian Geier <notifications@github.com> wrote:
>depending on their definition of fun, [RFC
>5546](https://tools.ietf.org/html/rfc5546) support could be a nice
>challenge (though its probably too hard for total beginners)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/meta/issues/8#issuecomment-274955689

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by geier** [comment]
More possible projects (for khal) from the issue tracker
 * proportional time day view https://github.com/pimutils/khal/issues/311
 * support for "travel time" https://github.com/pimutils/khal/issues/533
 * better creation of VTIMEZONES, e.g. by creating a cache of them https://github.com/pimutils/khal/issues/146
 * better support for recurrence rules https://github.com/pimutils/khal/issues/199 https://github.com/pimutils/khal/issues/62

As said before, one of you be needed as a backup mentor, in case I am not available in summer.

**Comment by untitaker** [comment]
Thats totally fine by me, though I might hit you with many questions as I'm not that familiar with timezones and recurrence anymore.

On 25 January 2017 14:03:26 CET, Christian Geier <notifications@github.com> wrote:
>More possible projects (for khal) from the issue tracker
>* proportional time day view
>https://github.com/pimutils/khal/issues/311
>* support for "travel time" https://github.com/pimutils/khal/issues/533
>* better creation of VTIMEZONES, e.g. by creating a cache of them
>https://github.com/pimutils/khal/issues/146
>* better support for recurrence rules
>https://github.com/pimutils/khal/issues/199
>https://github.com/pimutils/khal/issues/62
>
>As said before, one of you be needed as a backup mentor, in case I am
>not available in summer.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/meta/issues/8#issuecomment-275102645

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
I've submitted vdirsyncer on its own. Given that @geier has no time I think it'd be better to just submit todoman for now. @hobarrera please fill out that one for yourself, and enter me as mentor if you don't have time (btw you need to sort-of guarantee that you will have time if you're a mentor, see http://railsgirlssummerofcode.org/guide/projects/)

**Comment by hobarrera** [comment]
I intend to apply, but looks like sign in is [currently broken](https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/635), so I can't (same applied yesterday). 😞
